### ISSUE TITLE
Typecheck variables in config files

### ISSUE THREAD

**Issue by teunis90** [Nextpertise/autorsyncbackup#14]
Today we got a failed backup due to a config file typo:

    Reading main config from /etc/autorsyncbackup/main.yaml
    Writing to logfile /var/log/autorsyncbackup/autorsyncbackup.log
    Starting AutoRsyncBackup
    Traceback (most recent call last):
     File "/usr/local/bin/autorsyncbackup", line 48, in <module>
       director.processBackupStatus(job)
     File "/usr/local/share/autorsyncbackup/src/director.py", line 236, in processBackupStatus
       job.backupstatus['fileset'] = ':'.join(job.fileset)
    TypeError: sequence item 0: expected string, int found

We should not only check the YAML file for vadility but also type check the individual variables.

**Comment by teunis90** [comment]
Anybody a good idea how to accomplish this?
