### ISSUE TITLE
TypeError: unbound method deleteHistory() must be called with jobrunhistory instance as first argument (got nothing instead)

### ISSUE THREAD

**Issue by teunis90** [Nextpertise/autorsyncbackup#22]
Since the last PR I got the following error:
```
Traceback (most recent call last):
 File "/usr/local/bin/autorsyncbackup", line 141, in <module>
   runBackup(options.job, options.dryrun)
 File "/usr/local/bin/autorsyncbackup", line 88, in runBackup
   jobrunhistory.deleteHistory()
TypeError: unbound method deleteHistory() must be called with jobrunhistory instance as first argument (got nothing instead)
```

**Comment by teunis90** [comment]
Line 88 is there since: 678e76a

See: https://github.com/Nextpertise/autorsyncbackup/commit/678e76a5b0f7175a202073b84d9052c88ed9cf57#diff-eccfa481e7ac36383771768c084ec68e
