### ISSUE TITLE
Crash when calling hook while using rsync protocol

### ISSUE THREAD

**Issue by teunis90** [Nextpertise/autorsyncbackup#23]
```
ERROR: Error while connecting to host (host.domain.tld) - Authentication failed.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/src/autorsyncbackup/src/lib/jobthread.py", line 15, in run
    self.executeJob(self.q)
  File "/usr/src/autorsyncbackup/src/lib/jobthread.py", line 29, in executeJob
    self.director.executeRsync(job, latest)
  File "/usr/src/autorsyncbackup/src/lib/director.py", line 47, in executeRsync
    self.executeJobs(job, job.afterRemoteHooks)
  File "/usr/src/autorsyncbackup/src/lib/director.py", line 39, in executeJobs
    raise CommandException('Hook %s failed to execute' % c['script'])
CommandException: Hook /bin/ls -l failed to execute
```

**Comment by teunis90** [comment]
@lnoor However I got an e-mail with the text: "1 jobs OK - 0 jobs FAILED". Should we mark the backup as failed if the command fails?

**Comment by teunis90** [comment]
Btw: the "continueonerror" flag doesn't have any effect on the outcome of the backup e-mail.
